# https://docs.readthedocs.io/en/latest/yaml-config.html

build:
  image: latest

formats:
    - epub
    - pdf

python:
    version: 3.6
    
requirements_file: 
    requirements/requirements_doc.txt
